/employee:
  get:
   responses: 
     200:
       body: 
         application/json:
           example: |
             [{"ID": 1,"age":20,"name":"girija",
               "salary":30000},{"ID": 2,"age": "30",                                               "name": "chandana","salary":40000}]
